// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sojhyduhenphvbxvjvpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvamh5ZHVoZW5waHZieHZqdnB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNzYwMzIsImV4cCI6MjA2Njk1MjAzMn0.OnlJjB6TsQy5kWGQzd2uA-3XdGY6ReLGMsQsAimcJrE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});